# Generated by Django 5.0.1 on 2024-02-05 08:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=80)),
                ('email_client', models.EmailField(max_length=254)),
                ('phone_client', models.CharField(help_text='Номер телефона должен быть введен в формате: +7 xxx-xxx-xx-xx', max_length=12, validators=[django.core.validators.RegexValidator('^\\d\\d \\d\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d')])),
                ('adress_client', models.CharField(max_length=180)),
                ('date_client', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=80)),
                ('text_product', models.TextField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_product', models.IntegerField()),
                ('date_product', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_order', models.DateField(auto_now_add=True)),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.client')),
                ('product_order', models.ManyToManyField(to='storeapp.product')),
            ],
        ),
    ]
